// Hermetic fixture server for the cockpit screenshot harness (docs/07 CU5).
// Serves the BUILT cockpit (src/cockpit/dist) AND a faithful stand-in for the
// live API — the exact envelope shapes the real FastAPI serves — from the
// captured fixtures (tools/build_cockpit_fixture.py). This lets CI render the
// real cockpit board and run the ask/highlight flow WITHOUT the Python solver
// in the browser test. The live acceptance moment uses the real API instead.
import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { extname, join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST = resolve(__dirname, "..", "..", "src", "cockpit", "dist");
const FIX = resolve(__dirname, "fixtures");
const PORT = parseInt(process.env.PORT || "5199", 10);

// Two hermetic fixture sets, keyed by schedule id → its directory:
//   * the SATURATED multi_route (read-only interim-A regressions)
//   * the DISTINCT-rate multi_route (the 3.2b gesture surface — real ghosts +
//     canned sandbox verdicts). See tools/build_cockpit_fixture.py.
const DIRS = {
  "sched-multi-route-fixture": FIX,
  "sched-multi-route-distinct": resolve(FIX, "distinct"),
  // the hand-authored planner-surface fixture (Session 4.2): closures /
  // maintenance / overtime / setup / a split op / standing pin / customers.
  "sched-planner-fixture": resolve(FIX, "planner"),
  // the SLICED (rolling-horizon) fixtures (Session 4B.3a CU2): a real assembled
  // contract-1.7 document — committed frozen front + active window + a POPULATED
  // beyond-horizon tray; and an EMPTY-tray variant for the empty-state screenshot.
  "sched-rolling-fixture": resolve(FIX, "rolling"),
  "sched-rolling-empty": resolve(FIX, "rolling_empty"),
  // Session 4B.6a CU4: the SAME 40-order plant with a tight DECLARED derate, so
  // machine-weeks actually bind. At the plant's real 0.85 the demo book loads
  // the coarse zone to a few percent and no cell is hot — the density band's
  // binding-cell tooltip had nothing to be screenshotted against.
  "sched-rolling-coarse-hot": resolve(FIX, "rolling_coarse_hot"),
};
// An accepted edit mints a new version id ``<base>-edit`` (CU1); a CHAINED edit
// appends another ``-edit``. All map back to the base fixture directory so a
// rebind serves a coherent document (the harness asserts the state transitions,
// not a distinct moved-bar fixture). Strip EVERY trailing ``-edit`` so chained
// versions (``<base>-edit-edit``) still resolve to the base dir (session 3.8).
// The fixture dir a schedule id resolves to, or null when this server knows no
// such schedule. Kept distinct from dirFor (which falls back to the base set for
// the ancillary routes) so the DOCUMENT routes can answer 404 for an unknown id
// exactly as the real API does — the hotfix CU1 not-found path is otherwise
// untestable, because every id used to serve the base fixture.
const knownDir = (id) => {
  const ex = _EXTRA.find((e) => e.id === id);       // an injected newer schedule
  if (ex) return DIRS[ex.base] || FIX;
  return DIRS[id] || DIRS[id.replace(/(-edit)+$/, "")] || null;
};
const dirFor = (id) => knownDir(id) || FIX;
// On-demand pricing state (session 3.3 CU1): ops POSTed for pricing this
// session, keyed "<scheduleId>|<opId>". A GET /alternatives merges their ghosts.
const _PRIMED = new Set();
// Accepted edits this session, keyed by the new -edit version id → its decision.
// The edit-domain "summarize my changes" answer (CU2/CU5) is synthesized from
// this (the base run carries no edit evidence hermetically — the fixture server
// stands in for the real edit-domain, its established role).
const _EDITS = new Map();
// THE FROZEN BOUNDARY (Session 4B.28 Item 1): boundary children minted this
// session, new schedule id → the child document. The document itself is
// GENERATED BY THE REAL PYTHON MODULE (tools/build_boundary_fixture.py) and
// committed, so the harness proves the cockpit's DISPATCH — a real drag of the
// real handle sending the real requests and rendering what comes back — while
// `tests/test_frozen_boundary.py` proves the ruling. A hand-authored plan here
// would be a second implementation of R-F1 living in a JSON file.
const _BOUNDARY = new Map();
// Version lifecycle (session 3.8): a schedule's parent (recorded on accept), and
// the superseded set + successor map (populated on publish — publish supersedes
// the parent, whose successor is the published child). Editing/asking calls
// against a superseded id answer 409 "is superseded" exactly as the real API
// does, so the multi-cycle regression bites if a rebind ever leaves the cockpit
// stale-bound. Reset per test via POST /__test__/reset so a publish in one test
// never supersedes a base fixture the next test boots against.
let _PARENT = new Map();
let _SUPERSEDED = new Set();
let _SUCCESSOR = new Map();
// Session 4.4: injected "newer schedules" that appear in the DATA-ROOT listing
// while a tab is bound to an older one — the resubmit-while-viewing case. Each is
// {id, base, created_at, status, submission_id}; a GET /schedules merges them AND
// each resolves as a real schedule (doc/meta served from its `base` fixture dir),
// so an auto-follow reload actually lands on a coherent board. Cleared per test.
let _EXTRA = [];
// Session 4B.23: forced beat behaviour, so the guard can produce a REAL failure
// rather than assert against a hand-written state object. {beat_one, beat_two}:
//   beat_one: "undetermined" — a 200 carrying UNKNOWN / feasible:false. THE
//             DEFECT'S OWN SHAPE: on the dense demo board this is what beat one
//             actually returned, and the cockpit read it as "impossible".
//   beat_one: "error" / beat_two: "error" — a 503, i.e. a beat that could not be
//             completed at all.
let _FORCE = {};
function resetState() {
  _PRIMED.clear(); _EDITS.clear(); _BOUNDARY.clear();
  _PARENT = new Map(); _SUPERSEDED = new Set(); _SUCCESSOR = new Map();
  _EXTRA = [];
  _FORCE = {};
}
const extraFor = (id) => _EXTRA.find((e) => e.id === id) || null;
const supersededError = (res, sid) => {
  res.writeHead(409, { "content-type": "application/json" });
  return res.end(errEnv(409, `schedule ${sid} is superseded`));
};
// R-T2 (Session 4B.3b) — the harness stand-in for the two-beat contract. A
// stable correlation id per (schedule, pin), a beat-one ghost synthesized from
// the canned beat-two entry (feasibility + placement, NO money), and the layered
// beat-two enrichment (correlation + cost decomposition summing to the verdict +
// affected orders + driver) injected when a fixture doesn't already carry it.
function _corrId(sid, pin) {
  const raw = `${sid}|${pin.pin_op_id}|${pin.pin_resource_id}|${pin.pin_start_iso}`;
  let h = 0;
  for (let i = 0; i < raw.length; i++) { h = (h * 31 + raw.charCodeAt(i)) | 0; }
  return "corr-" + (h >>> 0).toString(16).padStart(8, "0");
}
function _feasibilityFrom(canned, pin, sid) {
  if (!canned) return null;
  const feasible = !!canned.feasible && canned.outcome !== "no_verdict";
  const pinMove = (canned.moves || []).find((m) => m.pinned);
  const placement = feasible ? [{
    operation_ref: pin.pin_op_id,
    resource_id: pin.pin_resource_id || (pinMove && pinMove.to_resource),
    start: pin.pin_start_iso || (pinMove && pinMove.to_start),
    end: pinMove ? pinMove.to_start : pin.pin_start_iso,
    pinned: true,
  }] : [];
  return {
    feasible, within_budget: true, wall_time_s: 0.02, budget_s: 2.0,
    status: feasible ? "FEASIBLE" : "INFEASIBLE",
    // Session 4B.23: beat one's THREE-state verdict, mirroring
    // mre.modules.sandbox.classify_feasibility. The synthesized ghost only ever
    // stands for a PROVEN case; UNDETERMINED is reached through /__test__/force.
    verdict: feasible ? "possible" : "impossible",
    message: feasible ? "this placement is possible — pricing it now"
                      : "this placement isn't possible here",
    placement,
    pin: { operation_ref: pin.pin_op_id, resource_id: pin.pin_resource_id,
           start: pin.pin_start_iso },
  };
}
function _enrichBeatTwo(result, pin, sid) {
  if (!result.correlation_id) result.correlation_id = _corrId(sid, pin);
  if (result.no_committed_work_changes == null) result.no_committed_work_changes = true;
  // a ledger-backed cost delta + a decomposition summing EXACTLY to it (the
  // real backend derives this from the re-solve ledger; the harness supplies a
  // coherent stand-in when the fixture doesn't carry one).
  if (result.feasible && result.cost_delta_abs == null && result.delta_abs != null) {
    result.cost_delta_abs = Math.round((result.delta_abs / 100) * 100) / 100;
    result.cost_delta_pct = result.delta_pct;
  }
  if (result.feasible && result.cost_lines == null) {
    const total = result.cost_delta_abs || 0;
    result.cost_lines = [
      { line: "tardiness", delta: 0 },
      { line: "setup", delta: 0 },
      { line: "production (regular)", delta: Math.round(total * 100) / 100 },
      { line: "production (overtime)", delta: 0 },
      { line: "other placement changes", delta: 0 },
    ];
  }
  if (result.feasible && result.affected_orders == null) result.affected_orders = [];
  if (result.feasible && result.lateness_delta_min == null) result.lateness_delta_min = 0;
  if (result.feasible && result.dominant_driver == null) {
    result.dominant_driver = { code: "COST_TRADEOFF",
      phrase: "it was the cheaper option once every cost was weighed", hedge: null };
  }
}
const load = async (name, dir = FIX) => JSON.parse(await readFile(join(dir, name), "utf-8"));
const loadMaybe = async (name, dir) => {
  const full = join(dir, name);
  return existsSync(full) ? JSON.parse(await readFile(full, "utf-8")) : null;
};
const MIME = {
  ".html": "text/html", ".js": "text/javascript", ".css": "text/css",
  ".json": "application/json", ".svg": "image/svg+xml", ".map": "application/json",
};
const envelope = (data) => JSON.stringify({ api_version: "1", data });
const errEnv = (code, message) => JSON.stringify({ api_version: "1", error: { code, message } });

async function body(req) {
  const chunks = [];
  for await (const c of req) chunks.push(c);
  return Buffer.concat(chunks).toString("utf-8");
}

const server = createServer(async (req, res) => {
  try {
    const url = new URL(req.url, `http://localhost:${PORT}`);
    const p = url.pathname;

    // ---- API stand-in (same envelopes as mre.api.app) -------------------
    if (p === "/health") {
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope({ status: "ok", api_version: "1" }));
    }
    // Test-only: clear per-session lifecycle state so each test starts clean
    // (a publish in one test must not supersede the base a later test boots).
    if (p === "/__test__/reset" && req.method === "POST") {
      resetState();
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope({ reset: true }));
    }
    // Session 4.4: inject a "newer schedule" into the data-root listing to drive
    // the resubmit-while-viewing auto-follow. Body {id, base, created_at?,
    // status?, submission_id?}. `base` names the fixture dir its doc/meta serve
    // from so an auto-follow lands on a coherent board.
    // Session 4B.23: force a beat to behave badly. Body {beat_one, beat_two}.
    if (p === "/__test__/force" && req.method === "POST") {
      _FORCE = JSON.parse((await body(req)) || "{}");
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope({ force: _FORCE }));
    }
    if (p === "/__test__/add-schedule" && req.method === "POST") {
      const b = JSON.parse((await body(req)) || "{}");
      _EXTRA.push({
        id: b.id, base: b.base || "sched-multi-route-distinct",
        created_at: b.created_at || "2026-01-05T11:00:00Z",
        status: b.status || "proposed",
        submission_id: b.submission_id ?? "sub-resubmit",
        generation: b.generation ?? null,
        // Session 4B.34 (R-GP1): a lineage child needs a PARENT and a SNAPSHOT —
        // the two facts `lineage.childOrigin` reads to tell a boundary ceremony
        // (which shares its parent's snapshot) from an accepted planner edit
        // (which mints `snap-edit-…`). Serving the doc from `base` is what makes
        // an injected child placement-IDENTICAL to its parent, which is exactly
        // the authority-only specimen the ruling is about.
        parent_schedule_id: b.parent_schedule_id ?? null,
        snapshot_id: b.snapshot_id ?? null,
      });
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope({ added: b.id }));
    }
    if (p === "/schedules" && req.method === "GET") {
      // static fixtures (tied created_at → none is "newer" than another) + any
      // injected newer schedules, ordered oldest→newest as the real API does.
      const metas = [];
      for (const dir of new Set(Object.values(DIRS))) {
        const m = await loadMaybe("meta.json", dir);
        if (m && !_SUPERSEDED.has(m.id)) metas.push(m);
      }
      for (const e of _EXTRA) {
        metas.push({ id: e.id, status: _SUPERSEDED.has(e.id) ? "superseded" : e.status,
          created_at: e.created_at, submission_id: e.submission_id,
          is_scenario: 0, contract_version: "1.3" });
      }
      metas.sort((a, b2) => String(a.created_at || "").localeCompare(String(b2.created_at || "")));
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope({ schedules: metas }));
    }
    const mSched = p.match(/^\/schedules\/([^/]+)$/);
    if (mSched && req.method === "GET") {
      const sid = mSched[1];
      // A BOUNDARY CHILD is served verbatim: it is a whole document the real
      // module produced, and re-deriving it here would be the second
      // implementation this fixture exists to avoid. Checked BEFORE knownDir,
      // because a `-thaw` id is not in DIRS and is not one of the `-edit` suffixes
      // knownDir strips — so the unknown-id 404 would fire on a version this
      // server itself minted one request ago.
      if (_BOUNDARY.has(sid)) {
        res.writeHead(200, { "content-type": "application/json" });
        return res.end(envelope(_BOUNDARY.get(sid)));
      }
      const dir = knownDir(sid);
      if (!dir) {                                   // unknown id → 404 (CU1)
        res.writeHead(404, { "content-type": "application/json" });
        return res.end(errEnv(404, `unknown schedule ${sid}`));
      }
      const doc = await load("schedule.json", dir);
      // An accepted -edit version reflects its pin: relocate the pinned op's
      // assignment to the pin placement so a rebind actually REFLOWS it (R-M1
      // motion end-states need a real move to assert against). A CHAINED edit
      // composes EVERY ancestor's pin (session 3.8), so a bar committed in an
      // earlier cycle stays where it was put through later cycles.
      const pins = [];
      for (let cur = sid; _EDITS.has(cur); cur = _PARENT.get(cur)) {
        const d = _EDITS.get(cur);
        if (d && d.pin) pins.push(d.pin);
        if (!_PARENT.has(cur)) break;
      }
      for (const pin of pins) {
        const a = (doc.assignments || []).find((x) => x.operation_ref === pin.pin_op_id);
        if (a && a.chunks && a.chunks.length) {
          const span = new Date(a.chunks[a.chunks.length - 1].end) - new Date(a.chunks[0].start);
          a.resource_id = pin.pin_resource_id;
          a.chunks[0].start = pin.pin_start_iso;
          a.chunks[a.chunks.length - 1].end = new Date(new Date(pin.pin_start_iso).getTime() + span).toISOString();
          // R-DP8 CU2: a pinned op carries a STANDING commitment — mark it so the
          // board renders the standing-pin marker (mirrors the real assembler,
          // which sets standing_pin from the version's cumulative lineage pins).
          a.standing_pin = true;
        }
      }
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope(doc));
    }
    const mMeta = p.match(/^\/schedules\/([^/]+)\/meta$/);
    if (mMeta && req.method === "GET") {
      const sid = mMeta[1];
      const metaDir = knownDir(sid);
      if (!metaDir) {                               // unknown id → 404 (CU1)
        res.writeHead(404, { "content-type": "application/json" });
        return res.end(errEnv(404, `unknown schedule ${sid}`));
      }
      const meta = { ...(await load("meta.json", metaDir)), id: sid };
      const ex = extraFor(sid);
      if (ex) {
        meta.created_at = ex.created_at; meta.status = ex.status;
        meta.submission_id = ex.submission_id;
        if (ex.generation != null) meta.generation = ex.generation;
        if (ex.parent_schedule_id != null) meta.parent_schedule_id = ex.parent_schedule_id;
        if (ex.snapshot_id != null) meta.snapshot_id = ex.snapshot_id;
      }
      const dec = _EDITS.get(sid);
      // an -edit version reads as proposed/published; a superseded one carries
      // its live successor so the cockpit can offer "view current" (CU3).
      if (_SUPERSEDED.has(sid)) {
        meta.status = "superseded";
        meta.successor_id = _SUCCESSOR.get(sid) || null;
      } else if (dec) {
        meta.status = dec.published ? "published" : "proposed";
      }
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope(meta));
    }
    const mInteract = p.match(/^\/schedules\/([^/]+)\/interaction$/);
    if (mInteract && req.method === "GET") {
      // the Tier-0 payload, served separately (contract 1.3, R-T1d). loadMaybe +
      // 404 when a fixture has none (a rolling/1.7 doc carries no interaction
      // payload) — mirrors the real API, and never writes headers before a load
      // that can fail (the ERR_HTTP_HEADERS_SENT crash class).
      const inter = await loadMaybe("interaction.json", dirFor(mInteract[1]));
      if (!inter) {
        res.writeHead(404, { "content-type": "application/json" });
        return res.end(errEnv(404, "no interaction payload for this schedule"));
      }
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope(inter));
    }
    // On-demand pricing (session 3.3 CU1): POST /alternatives/op/<op> primes the
    // op; a later GET /alternatives merges in its priced ghosts (replaying the
    // real append-to-pool behavior). Match this BEFORE the member-index route.
    const mOnDemand = p.match(/^\/schedules\/([^/]+)\/alternatives\/op\/([^/]+)$/);
    if (mOnDemand && req.method === "POST") {
      const [, sid, opId] = mOnDemand;
      const od = await loadMaybe("ondemand.json", dirFor(sid));
      if (od && od.op_id === opId) _PRIMED.add(`${sid}|${opId}`);
      res.writeHead(202, { "content-type": "application/json" });
      return res.end(envelope({ op_id: opId, status: "pricing" }));
    }
    // The full solved document behind one ghost (session 3.3 CU4): served as
    // member_<index>.json (404 when the fixture built none for this index).
    const mMember = p.match(/^\/schedules\/([^/]+)\/alternatives\/(\d+)$/);
    if (mMember && req.method === "GET") {
      const doc = await loadMaybe(`member_${mMember[2]}.json`, dirFor(mMember[1]));
      if (!doc) {
        res.writeHead(404, { "content-type": "application/json" });
        return res.end(errEnv(404, "no member document for this index"));
      }
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope(doc));
    }
    // Tier-1 ghosts (R-T1a) — the /alternatives payload. 404 when the fixture
    // built none (the read-only multi_route set): the drag surface stays green.
    const mAlt = p.match(/^\/schedules\/([^/]+)\/alternatives$/);
    if (mAlt && req.method === "GET") {
      const dir = dirFor(mAlt[1]);
      const alt = await loadMaybe("alternatives.json", dir);
      if (!alt) {
        res.writeHead(404, { "content-type": "application/json" });
        return res.end(errEnv(404, "no forced alternatives built"));
      }
      // merge any on-demand-priced members for ops primed this session (CU1)
      const od = await loadMaybe("ondemand.json", dir);
      if (od && _PRIMED.has(`${mAlt[1]}|${od.op_id}`)) {
        const have = new Set(alt.members.map((m) => m.member_index));
        for (const m of od.members || []) {
          if (!have.has(m.member_index)) alt.members.push(m);
        }
      }
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope(alt));
    }
    // BEAT ONE (R-T2, Session 4B.3b): a first-feasible feasibility ghost —
    // feasibility + placement + a correlation id, NO money (R-T2(1)). Synthesized
    // from the canned sandbox entry for this op (the harness stands in for the
    // real feasibility_ghost, whose end-to-end truth the Python tests prove). A
    // canned `feasibility.json` overrides per-op to force the CONTRADICTION cases.
    const mFeas = p.match(/^\/schedules\/([^/]+)\/sandbox\/feasibility$/);
    if (mFeas && req.method === "POST") {
      const sid = mFeas[1];
      if (_SUPERSEDED.has(sid)) return supersededError(res, sid);
      const dir = dirFor(sid);
      const pin = JSON.parse((await body(req)) || "{}");
      // Session 4B.23: the forced beat-one shapes.
      if (_FORCE.beat_one === "error") {
        res.writeHead(503, { "content-type": "application/json" });
        return res.end(errEnv(503, "feasibility worker unavailable"));
      }
      if (_FORCE.beat_one === "undetermined") {
        res.writeHead(200, { "content-type": "application/json" });
        return res.end(envelope({
          correlation_id: _corrId(sid, pin),
          feasible: false, within_budget: true, wall_time_s: 2.04, budget_s: 2.0,
          status: "UNKNOWN", verdict: "undetermined",
          message: "I couldn't finish checking this placement in 2s — that is my "
                   + "budget running out, not a verdict about the plant",
          placement: [],
          pin: { operation_ref: pin.pin_op_id, resource_id: pin.pin_resource_id,
                 start: pin.pin_start_iso },
        }));
      }
      const feas = await loadMaybe("feasibility.json", dir);
      const canned = feas && feas.by_op && feas.by_op[pin.pin_op_id];
      const sb = await loadMaybe("sandbox.json", dir);
      const sbCanned = (sb && sb.by_op && sb.by_op[pin.pin_op_id]) || (sb && sb.default);
      // A `contradiction` hint FORCES a beat-one/beat-two divergence (CU3):
      //   "infeasible" — beat one feasible (beat two's canned no_verdict makes it);
      //   "moved"      — beat one feasible but placing the op materially elsewhere
      //                  than beat two's pin (start shifted relative to THIS pin).
      let ghost;
      if (canned && canned.contradiction) {
        ghost = _feasibilityFrom({ ...(sbCanned || {}), feasible: true,
                                   outcome: "verdict",
                                   moves: [{ pinned: true, to_resource: pin.pin_resource_id,
                                             to_start: pin.pin_start_iso }] }, pin, sid);
        if (canned.contradiction === "moved" && ghost.placement[0]) {
          const shifted = new Date(Date.parse(pin.pin_start_iso) + 2 * 3600 * 1000).toISOString();
          ghost.placement[0].start = shifted;
        }
      } else {
        ghost = canned || _feasibilityFrom(sbCanned, pin, sid);
      }
      if (!ghost) {
        res.writeHead(404, { "content-type": "application/json" });
        return res.end(errEnv(404, "no canned feasibility for this fixture"));
      }
      ghost.correlation_id = _corrId(sid, pin);
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope(ghost));
    }
    // BEAT TWO — Tier-2 sandbox re-solve (R-DP1/R-T1c) — canned by pinned op.
    // Returns the outcome the fixture recorded for this op (verdict / flagged /
    // no_verdict), else the default verdict, ENRICHED with the R-T2 layered-card
    // fields (correlation id, cost decomposition, affected orders, driver) if the
    // fixture doesn't carry them (Session 4B.3b).
    const mSandbox = p.match(/^\/schedules\/([^/]+)\/sandbox$/);
    if (mSandbox && req.method === "POST") {
      if (_SUPERSEDED.has(mSandbox[1])) return supersededError(res, mSandbox[1]);
      // Session 4B.23: beat two could not be completed at all.
      if (_FORCE.beat_two === "error") {
        res.writeHead(503, { "content-type": "application/json" });
        return res.end(errEnv(503, "sandbox worker unavailable"));
      }
      const sb = await loadMaybe("sandbox.json", dirFor(mSandbox[1]));
      if (!sb) {
        res.writeHead(404, { "content-type": "application/json" });
        return res.end(errEnv(404, "no canned sandbox for this fixture"));
      }
      const pin = JSON.parse((await body(req)) || "{}");
      const result = { ...((sb.by_op && sb.by_op[pin.pin_op_id]) || sb.default) };
      _enrichBeatTwo(result, pin, mSandbox[1]);
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope(result));
    }
    // R-F1 (Session 4B.28 Item 1) — the boundary PREVIEW. Keyed by the target
    // instant, straight from the generated fixture. An instant the fixture does
    // not carry answers with a REFUSAL rather than a guess, which is also the
    // real API's shape for a move it cannot make.
    const mBPrev = p.match(/^\/schedules\/([^/]+)\/boundary\/preview$/);
    if (mBPrev && req.method === "POST") {
      const sid = mBPrev[1];
      if (_SUPERSEDED.has(sid)) return supersededError(res, sid);
      const reqBody = JSON.parse((await body(req)) || "{}");
      const canned = await loadMaybe("boundary_preview.json", dirFor(sid));
      // The generated fixture carries ONE plan per DIRECTION. A real drag lands
      // on whatever hour the pointer snapped to, so this resolves by direction
      // rather than by exact instant — the harness is proving the cockpit's
      // dispatch, and which of the two canned plans comes back is not what it
      // is asking about. The instant→plan mapping itself is proved in Python
      // (tests/test_frozen_boundary.py), against the module that owns it.
      const doc = await load("schedule.json", dirFor(sid));
      const frozen = Date.parse(doc.rolling.frozen_until);
      const want = Date.parse(reqBody.frozen_until);
      // The window edges are the SAME guard the real endpoint applies, mirrored
      // here for the same reason `_SUPERSEDED` and the digest check are: a
      // refusal branch the harness cannot reach is a refusal branch nothing
      // drives.
      const wStart = Date.parse(doc.rolling.window_start);
      const wEnd = Date.parse(doc.rolling.window_end);
      if (want < wStart || want > wEnd) {
        res.writeHead(200, { "content-type": "application/json" });
        return res.end(envelope({
          refused: true, code: want < wStart ? "before_window" : "after_window",
          sentence: want < wStart
            ? "The boundary cannot go earlier than the start of this window."
            : "The boundary cannot go past the end of this window — nothing "
              + "beyond it has been solved yet, so there is nothing to commit.",
        }));
      }
      let plan = null;
      if (canned && want !== frozen) {
        const dir = want < frozen ? "thaw" : "freeze";
        plan = Object.values(canned).find(
          (v) => !v.refused && v.direction === dir) || null;
      }
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope(plan || {
        refused: true, code: "no_change",
        sentence: "That is where the boundary already sits — nothing to change.",
      }));
    }
    // …and the APPLY. It checks the digest exactly as the real endpoint does, so
    // the harness can drive the stale-confirmation refusal without a server that
    // knows anything about boundaries.
    const mBApply = p.match(/^\/schedules\/([^/]+)\/boundary$/);
    if (mBApply && req.method === "POST") {
      const sid = mBApply[1];
      if (_SUPERSEDED.has(sid)) return supersededError(res, sid);
      const reqBody = JSON.parse((await body(req)) || "{}");
      const child = await loadMaybe("boundary_child.json", dirFor(sid));
      if (!child) {
        res.writeHead(200, { "content-type": "application/json" });
        return res.end(envelope({ refused: true, code: "not_rolling",
          sentence: "This board has no frozen boundary to move." }));
      }
      if (reqBody.expect_digest
          && reqBody.expect_digest !== child.boundary.digest) {
        res.writeHead(200, { "content-type": "application/json" });
        return res.end(envelope({ refused: true, code: "stale_confirmation",
          sentence: "The board changed between showing you that and this click, "
                  + "so I did not move the boundary." }));
      }
      const newId = `${sid}-thaw`;
      const doc = JSON.parse(JSON.stringify(child.document));
      doc.schedule_id = newId;
      _BOUNDARY.set(newId, doc);
      _PARENT.set(newId, sid);
      res.writeHead(201, { "content-type": "application/json" });
      return res.end(envelope({
        schedule_id: newId, parent_schedule_id: sid, status: "proposed",
        boundary: { ...child.boundary, authority: reqBody.authority },
      }));
    }
    // Accept a dropped bar's verdict (CU1): mint a new proposed version id and
    // echo a planner_edit decision. The delta rides from the canned sandbox so
    // the accepted card shows a real number.
    const mAccept = p.match(/^\/schedules\/([^/]+)\/accept$/);
    if (mAccept && req.method === "POST") {
      const sid = mAccept[1];
      if (_SUPERSEDED.has(sid)) return supersededError(res, sid);
      const pin = JSON.parse((await body(req)) || "{}");
      const sb = await loadMaybe("sandbox.json", dirFor(sid));
      const canned = (sb && sb.by_op && sb.by_op[pin.pin_op_id]) || (sb && sb.default) || {};
      // A chained edit appends another -edit so the id keeps advancing (CU1).
      const newId = `${sid}-edit`;
      const decision = {
        record_id: "dec-" + Math.random().toString(36).slice(2, 10),
        authority: pin.authority || "dev-planner",
        delta_abs: canned.delta_abs ?? null, delta_pct: canned.delta_pct ?? null,
        moved_count: (canned.moves || []).length, pin,
      };
      _EDITS.set(newId, decision);
      _PARENT.set(newId, sid);
      res.writeHead(201, { "content-type": "application/json" });
      return res.end(envelope({
        schedule_id: newId, parent_schedule_id: sid, status: "proposed", decision,
      }));
    }
    // Publish an accepted version (CU1): proposed → published, superseding the
    // prior version.
    const mPublish = p.match(/^\/schedules\/([^/]+)\/publish$/);
    if (mPublish && req.method === "POST") {
      const sid = mPublish[1];
      if (_SUPERSEDED.has(sid)) return supersededError(res, sid);
      // Supersede the IMMEDIATE parent (recorded on accept), whose live
      // successor becomes this published version (session 3.8 CU3). Mirrors
      // Registry.publish_schedule: proposed → published, parent → superseded.
      const parent = _PARENT.get(sid) || sid.replace(/(-edit)+$/, "");
      const superseded = [];
      if (parent && parent !== sid) {
        _SUPERSEDED.add(parent);
        _SUCCESSOR.set(parent, sid);
        superseded.push(parent);
      }
      const dec = _EDITS.get(sid);
      if (dec) dec.published = true;
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope({ schedule_id: sid, status: "published", superseded }));
    }
    // Session 4A.5c CU3(a) — BEAT ONE of the two-phase ask. Every canned answer
    // in this harness is a CONTRACTED one, so the honest fixture response is the
    // route tier with no waiting copy: the panel shows no waiting state and the
    // flow is exactly what it was. Served explicitly rather than left to 404 into
    // the SPA fallback, so the harness exercises the real request/response shape
    // instead of the client's catch branch.
    const mPre = p.match(/^\/schedules\/([^/]+)\/ask\/preflight$/);
    if (mPre && req.method === "POST") {
      if (_SUPERSEDED.has(mPre[1])) return supersededError(res, mPre[1]);
      await body(req);
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope({ tier: "route", waiting: "", intent: null }));
    }
    const mAsk = p.match(/^\/schedules\/([^/]+)\/ask$/);
    if (mAsk && req.method === "POST") {
      const sid = mAsk[1];
      if (_SUPERSEDED.has(sid)) return supersededError(res, sid);
      const { question } = JSON.parse((await body(req)) || "{}");
      // CU5 closing beat: "summarize my changes" on an accepted -edit version →
      // synthesize the edit narrative from the remembered accept (the base run
      // has no edit evidence hermetically). The real decomposed answer is proven
      // by the Python end-to-end test against the live API.
      const dec = _EDITS.get(sid);
      if (dec && /summar|what.*chang|what i chang|my (change|edit)/i.test(question)) {
        const d = dec.delta_abs;
        const dstr = d == null ? "cost unknown"
          : `${d >= 0 ? "+" : "−"}$${Math.abs(d).toLocaleString()}`;
        const op8 = (dec.pin?.pin_op_id || "").slice(0, 8);
        const answer = `You accepted 1 edit on this version (${dstr} total):\n`
          + `  - pinned op ${op8} to its machine · ${dstr} · by ${dec.authority}\n\n`
          + `register: testimony`;
        res.writeHead(200, { "content-type": "application/json" });
        return res.end(envelope({
          question, answer,
          bundle: { register: "testimony", subject_type: "edits",
                    cited_refs: { operations: [dec.pin?.pin_op_id].filter(Boolean),
                                  resources: [], demands: [] } },
        }));
      }
      const asks = await load("asks.json", dirFor(sid));
      const hit = asks[question];
      if (!hit) {
        res.writeHead(404, { "content-type": "application/json" });
        return res.end(errEnv(404, `no canned answer for: ${question}`));
      }
      res.writeHead(200, { "content-type": "application/json" });
      return res.end(envelope(hit));
    }

    // ---- static: the built cockpit --------------------------------------
    let file = p === "/" ? "/index.html" : p;
    let full = join(DIST, file);
    if (!existsSync(full)) full = join(DIST, "index.html"); // SPA fallback
    const data = await readFile(full);
    res.writeHead(200, { "content-type": MIME[extname(full)] || "application/octet-stream" });
    return res.end(data);
  } catch (e) {
    res.writeHead(500, { "content-type": "application/json" });
    res.end(errEnv(500, String(e.message || e)));
  }
});

server.listen(PORT, () => console.log(`cockpit fixture server on http://localhost:${PORT}`));
