"""DRAFT ROUTE — MACHINE-GENERATED, NOT WIRED INTO DISPATCH.

Generated by tools/promotion_dossier.py for cluster:
    late-orders|no-subject|lateness_set
from 2 synthesis answer(s) in _ai_exam_scratch/dossier_replay/ledger.jsonl.

THIS FILE IS NOT IMPORTED BY ANYTHING. It sits under docs/promotions/drafts/ on
purpose: R-AI5(7) makes promotion a REVIEWED change, and a draft that any module
could import would be a promotion nobody signed.

What a reviewing session does with it: read the assembly pattern below against the
dossier, decide whether a contracted route can honestly serve this shape, and — if
so — implement the real assembler in ``mre.modules.explainer`` with its authored
copy in ``mre.modules.ask_fallback_copy``, citing the dossier. The draft is
scaffolding, not the implementation: it names the readers the cluster's verified
answers actually used and the facts they proved, and it deliberately does NOT
guess at the planner-facing wording, which is authored copy and a human's.

EVIDENCE-ASSEMBLY PATTERN (from the cluster's verified transcripts):
      lateness_set()   x2
      placements_for_order(order=<order>)   x2
      cost_ledger()   x2
      placements_for_machine(machine=<machine>)   x1
      calendars(machine=<machine>)   x1

CLAIMS A CONTRACTED ROUTE MUST BE ABLE TO MAKE (verified in synthesis):
      - Only one order is late: ORD-05, by 890 minutes (nearly 15 hours).
      - ORD-05 is scheduled on CUT-01 from 07:00 to 14:50 on 2026-01-06, finishing at 14:50 UTC, but its due date is 2026-01-05 at 23:59:59 UTC — already past by the time it runs.
      - ORD-05 is the only late order, finishing 890 minutes (nearly 15 hours) past its due date of 2026-01-05 23:59:59Z.
      - ORD-05 is scheduled on CUT-01 from 2026-01-06 07:00 to 14:50, which is the day after its due date.
"""
from __future__ import annotations

from typing import Any


DRAFT_ROUTE_ID = "lateness-cause"
DRAFT_PARAMS = ['machine', 'order']


def assemble_draft(explainer: Any, params: dict):
    """Pre-computed facts for the draft route.

    Each reader below is the SAME reader the synthesis tier called, reached the way
    a contracted assembler reaches it. The tool surface is a thin wrapper over these
    (Session 4A.5b CU1), so a promotion is not a reimplementation — it is the same
    evidence assembled deterministically instead of agentically.
    """
    from mre.modules.evidence_tools import EvidenceToolbox
    toolbox = EvidenceToolbox(explainer)

    facts: dict = {}
    records: list = []
    # lateness_set: called 2x across the cluster's verified answers
    _lateness_set = toolbox.call("lateness_set", {})
    records.extend(_lateness_set.record_ids)
    # placements_for_order: called 2x across the cluster's verified answers
    _placements_for_order = toolbox.call("placements_for_order", {"order": params.get("order")})
    records.extend(_placements_for_order.record_ids)
    # cost_ledger: called 2x across the cluster's verified answers
    _cost_ledger = toolbox.call("cost_ledger", {})
    records.extend(_cost_ledger.record_ids)
    # placements_for_machine: called 1x across the cluster's verified answers
    _placements_for_machine = toolbox.call("placements_for_machine", {"machine": params.get("machine")})
    records.extend(_placements_for_machine.record_ids)
    # calendars: called 1x across the cluster's verified answers
    _calendars = toolbox.call("calendars", {"machine": params.get("machine")})
    records.extend(_calendars.record_ids)

    return facts, records


def authored_copy_skeleton() -> dict:
    """The authored strings this route needs. EMPTY ON PURPOSE.

    Planner-facing copy is authored by a human in ``ask_fallback_copy`` (R-AI1(c):
    intelligence accrues only in reviewable artifacts). Generating it here would
    put model prose on the answer surface through the back door, which is the one
    thing the whole tier is built to prevent."""
    return {
        # "Only one order is late: ORD-05, by 890 minutes (nearly 15 hours)...."
        # "ORD-05 is scheduled on CUT-01 from 07:00 to 14:50 on 2026-01-06, finis..."
        # "ORD-05 is the only late order, finishing 890 minutes (nearly 15 hours)..."
        # "ORD-05 is scheduled on CUT-01 from 2026-01-06 07:00 to 14:50, which is..."
    }
