"""Errand 4B.22a: prove the generator change left `pilot_scale` byte-identical.

The 4B.22a errand added two knobs to `_apply_pilot_scale` (`past_due_share`,
`lead_p50_override`) so the new `demo_board` preset could reuse pilot_scale's
authored physics at a demo density. `pilot_scale` carries every rolling
regression golden the programme owns, so "unchanged" has to be a MEASUREMENT,
not a claim.

The subtle way this could have gone wrong is not the emitted values: it is the
RANDOM STREAM. An unconditional `rng.random()` for the past-due draw would shift
every subsequent draw in the order loop, so the same seed would emit a different
book while every line of authored physics stayed the same. The past-due branch
is guarded by `past_due_share > 0 and ...` precisely so nothing is drawn at the
default, and this script is what checks it.

    python tools/spikes/demo_board_4b22a/prove_pilot_scale_unchanged.py \
        --against _4b22a_scratch/baseline_pilot40

`--against` is a submission generated by the PREVIOUS code. Without it the
script regenerates twice under the new code and can only prove self-consistency,
which proves nothing about the change; it says so and exits non-zero.

`manifest.json` is EXCLUDED from the comparison and named here rather than
quietly dropped: the generator stamps a fresh `extract_timestamp` into it on
every run, so it is byte-different between any two generations of the same
world. `feel_fixture.json` is excluded for the same class of reason — 4B.22a
added three descriptive keys to the marker (past_due_share_declared,
past_due_orders_generated, lead_p50_effective) and the marker is documentation,
not data. Every file the SOLVER reads is compared.
"""
from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO / "tools"))

# Excluded, and why — see the module docstring. Not a silent filter.
EXCLUDED = {
    "manifest.json": "carries a fresh extract_timestamp on every generation",
    "feel_fixture.json": "a descriptive marker; 4B.22a added three keys to it",
}


def _hashes(d: Path) -> dict[str, str]:
    out = {}
    for p in sorted(d.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(d).as_posix()
        if rel in EXCLUDED:
            continue
        out[rel] = hashlib.sha256(p.read_bytes()).hexdigest()
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--against", default=None,
                    help="a pilot_scale submission generated by the PREVIOUS code")
    ap.add_argument("--orders", type=int, default=40)
    ap.add_argument("--seed", type=int, default=1)
    args = ap.parse_args(argv)

    from generate_erp_dataset import generate

    tmp = Path(tempfile.mkdtemp(prefix="pilot-unchanged"))
    fresh = tmp / "pilot_scale"
    generate(fresh, scenario="pilot_scale", orders=args.orders, seed=args.seed)
    new = _hashes(fresh)

    for name, why in EXCLUDED.items():
        print(f"excluded: {name} ({why})")

    if not args.against:
        print("\n!! NO --against BASELINE. This run proves only that the new "
              "code is self-consistent, which is not the claim. Generate a "
              "baseline from the previous commit and re-run.", file=sys.stderr)
        return 2

    old = _hashes(Path(args.against))
    only_old = sorted(set(old) - set(new))
    only_new = sorted(set(new) - set(old))
    differ = sorted(k for k in set(old) & set(new) if old[k] != new[k])

    print(f"\npilot_scale {args.orders} orders / seed {args.seed}: "
          f"{len(new)} compared file(s)")
    for k in sorted(set(old) & set(new)):
        print(f"  {'SAME ' if old[k] == new[k] else 'DIFFER'}  {k}")
    if only_old:
        print(f"  MISSING under the new code: {only_old}")
    if only_new:
        print(f"  ADDED under the new code:   {only_new}")

    if differ or only_old or only_new:
        print("\n!! pilot_scale CHANGED. Every rolling golden taken on it is "
              "now suspect.", file=sys.stderr)
        return 1

    print("\npilot_scale is BYTE-IDENTICAL across the 4B.22a generator change.")
    shutil.rmtree(tmp, ignore_errors=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
