"""Build the FROZEN-BOUNDARY harness fixtures (Session 4B.28 Item 1).

The cockpit harness is hermetic: no Python runs in the browser test, so the
fixture server serves canned API responses and the browser test proves the
DISPATCH — that a real drag of the real handle sends the real requests and
renders what comes back. The SERVER's own truth is proved by
``tests/test_frozen_boundary.py`` against ``mre.modules.frozen_boundary``.

The canned responses are therefore generated BY THAT SAME MODULE, here, rather
than hand-authored. A hand-authored preview would be a second implementation of
the ruling living in a JSON file, and the first time the two disagreed the
browser test would keep passing against the wrong one.

    PYTHONHASHSEED=0 python tools/build_boundary_fixture.py

Writes, beside the rolling fixture it reads:

    tests/cockpit/fixtures/rolling/boundary_preview.json   the plan (both
                                                           directions, keyed by
                                                           the target instant)
    tests/cockpit/fixtures/rolling/boundary_child.json     the document a
                                                           committed thaw mints
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from mre.modules.frozen_boundary import (  # noqa: E402
    BoundaryRefused, apply_move, plan_move,
)

FIXTURE_DIR = REPO / "tests" / "cockpit" / "fixtures" / "rolling"
UTC = timezone.utc


def _dt(raw: str) -> datetime:
    d = datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
    return d if d.tzinfo else d.replace(tzinfo=UTC)


def main() -> int:
    doc_path = FIXTURE_DIR / "schedule.json"
    doc = json.loads(doc_path.read_text(encoding="utf-8"))
    rolling = doc.get("rolling")
    if not rolling:
        print(f"{doc_path} is not a rolling document", file=sys.stderr)
        return 1

    frozen = _dt(rolling["frozen_until"])
    win_start = _dt(rolling["window_start"])
    win_end = _dt(rolling["window_end"])

    # TWO TARGETS, one per direction, chosen so BOTH are non-trivial on this
    # fixture — a thaw that thaws nothing would let the browser test pass while
    # rendering an empty confirmation beat.
    thaw_to = max(win_start, frozen - timedelta(hours=12))
    freeze_to = min(win_end, frozen + timedelta(hours=12))

    previews = {}
    for label, target in (("thaw", thaw_to), ("freeze", freeze_to)):
        try:
            plan = plan_move(doc, target.isoformat())
        except BoundaryRefused as ref:
            print(f"  {label}: REFUSED ({ref.code}) — {ref.sentence}")
            previews[target.isoformat()] = {"refused": True, "code": ref.code,
                                            "sentence": ref.sentence}
            continue
        previews[target.isoformat()] = {"refused": False, **plan.to_dict()}
        print(f"  {label} -> {target.isoformat()}: {plan.direction}, "
              f"{plan.count} placement(s)")

    # The child a COMMITTED THAW mints — the document the cockpit rebinds to, so
    # the browser test can assert the bars actually restyled.
    result = apply_move(doc, thaw_to.isoformat(), authority="dev-planner",
                        at=datetime(2026, 1, 5, 9, 0, tzinfo=UTC),
                        schedule_id=f"{doc['schedule_id']}-thaw")
    child = {
        "schedule_id": result.document["schedule_id"],
        "parent_schedule_id": doc["schedule_id"],
        "document": result.document,
        "pins": result.pins,
        "boundary": {**result.plan.to_dict(),
                     "authority": "dev-planner",
                     "decision_record_id": "rec-boundary-fixture"},
    }

    (FIXTURE_DIR / "boundary_preview.json").write_text(
        json.dumps(previews, indent=2), encoding="utf-8")
    (FIXTURE_DIR / "boundary_child.json").write_text(
        json.dumps(child, indent=2), encoding="utf-8")
    print(f"wrote {FIXTURE_DIR / 'boundary_preview.json'}")
    print(f"wrote {FIXTURE_DIR / 'boundary_child.json'}")
    print(f"  child: {len(result.plan.pinned_ops)} op(s) became standing pins")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
